// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExportPDF():Promise<void>;

export function InitialPath():Promise<string>;

export function OpenExternal(arg1:string):Promise<void>;

export function OpenFile():Promise<string>;

export function PendingPaths():Promise<Array<string>>;

export function ReadAsset(arg1:string,arg2:string):Promise<main.Asset>;

export function ReadDocument(arg1:string):Promise<main.Document>;

export function ResolveDocumentLink(arg1:string,arg2:string):Promise<string>;

export function StartWatching(arg1:string):Promise<void>;

export function StopWatching():Promise<void>;
