// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportPDF() {
  return window['go']['main']['App']['ExportPDF']();
}

export function InitialPath() {
  return window['go']['main']['App']['InitialPath']();
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function PendingPaths() {
  return window['go']['main']['App']['PendingPaths']();
}

export function ReadAsset(arg1, arg2) {
  return window['go']['main']['App']['ReadAsset'](arg1, arg2);
}

export function ReadDocument(arg1) {
  return window['go']['main']['App']['ReadDocument'](arg1);
}

export function ResolveDocumentLink(arg1, arg2) {
  return window['go']['main']['App']['ResolveDocumentLink'](arg1, arg2);
}

export function StartWatching(arg1) {
  return window['go']['main']['App']['StartWatching'](arg1);
}

export function StopWatching() {
  return window['go']['main']['App']['StopWatching']();
}
